name: UniqueUUID
main: fang.uniqueuuid.UniqueUUID
version: 1.1.0a
api-version: 1.18
author: Mr_Fang
description: 'Unique UUID'
commands:
  uniqueuuid:
    permission: uniqueuuid.admin
permissions:
  uniqueuuid.admin:
    default: op